name: iOS e2e tests

on: [pull_request, workflow_dispatch]
jobs:
  ios-e2e:
    name: iOS e2e
    timeout-minutes: 25
    runs-on: ["self-hosted"]
    # Cancel current builds if there's a newer commit on the same branch
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up github keys
        run:  git config core.sshCommand "ssh -i ~/.ssh/id_ed25519 -F /dev/null"
     
      - name: clean ios app step
        run: yarn clean:ios  > /dev/null 2>&1 || true

      - name: Set up ENV vars & scripts
        run: |
          source ~/.bashrc
          git clone git@github.com:rainbow-me/rainbow-env.git
          mv rainbow-env/dotenv .env && rm -rf rainbow-env 
          eval $CI_SCRIPTS
          sed -i''-e "s/\IS_TESTING=false/IS_TESTING=true/" .env && rm -f .env-e
      
      - name: Install deps via Yarn
        run: yarn setup-ci

      - name: Check for frozen lockfile
        run: yarn check-lockfile

      - name: Audit CI
        run:  yarn audit-ci --config audit-ci.jsonc

      - name: Lint
        run: yarn lint:ci

      - name: Install Pods
        run: yarn install-pods

      - name: Installing Maestro
        run: curl -Ls "https://get.maestro.mobile.dev" | bash

      - name: Installing Maestro dependencies
        run: |
          brew tap facebook/fb
          brew install facebook/fb/idb-companion

      - name: Build app for simulator
        working-directory: ios
        run: |
          xcrun xcodebuild \
            -project "Rainbow.xcodeproj" \
            -scheme "Rainbow" \
            -configuration "Release" \
            -sdk "iphonesimulator" \
            -destination "platform=iOS Simulator,name=iPhone 15 Pro" \
            -derivedDataPath "../build_output"
      
      - name: Setup e2e tests
        env:
          APP_PATH: './build_output/Build/Products/Release-iphonesimulator/Rainbow.app'
      
        run: |
          echo "Launching iOS Simulator"
          xcrun simctl boot "iPhone 15 Pro"
          echo "Installing app on Simulator"
          xcrun simctl install booted "${{ env.APP_PATH }}"
              
      - name: Run e2e tests (3 retries)
        timeout-minutes: 10 
        run: |
          i=0
          while [ $i -le 2 ]; do
          $HOME/.maestro/bin/maestro test e2e-new/test.yaml && break
          let i=i+1
          if [ $i -eq 3 ]; then
            echo "Failed after 3 attempts"
            exit 1
          fi
          done
     
      - name: Upload Test Artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: detox-artifacts
          path: artifacts/**

