name: iOS e2e tests

on: [pull_request, workflow_dispatch]
jobs:
  ios-e2e:
    name: iOS e2e
    timeout-minutes: 25
    runs-on: ["self-hosted"]
    # Cancel current builds if there's a newer commit on the same branch
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up github keys
        run:  git config core.sshCommand "ssh -i ~/.ssh/id_ed25519 -F /dev/null"

      - name: Set up ENV vars & scripts
        run: |
          source ~/.bashrc
          git clone git@github.com:rainbow-me/rainbow-env.git
          mv rainbow-env/dotenv .env && rm -rf rainbow-env 
          eval $CI_SCRIPTS
          sed -i''-e "s/\IS_TESTING=false/IS_TESTING=true/" .env && rm -f .env-e
      
      - name: Cache Yarn Dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ~/.cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - name: Cache Cocoapods
        uses: actions/cache@v2
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      
      - name: Install deps via Yarn
        run: yarn setup-ci

      - name: Check for frozen lockfile
        run: yarn check-lockfile

      - name: Audit & Lint CI
        run:  yarn audit-ci --config audit-ci.jsonc && yarn lint:ci

      - name: Install Pods
        run: yarn install-pods

      - name: Installing Maestro & dependencies
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          brew tap facebook/fb
          brew install facebook/fb/idb-companion

      - name: Build app for simulator
        working-directory: ios
        run: |
          xcrun xcodebuild \
            -scheme "Rainbow" \
            -workspace "Rainbow.xcworkspace" \
            -configuration "Release" \
            -sdk "iphonesimulator" \
            -destination "platform=iOS Simulator,name=iPhone 15 Pro" \
            -derivedDataPath "temp_build"
      
      - name: Setup e2e tests
        env:
          APP_PATH: './ios/temp_build/Build/Products/Release-iphonesimulator/Rainbow.app'
      
        run: |
          echo "Shutting down any running simulators..."
          xcrun simctl shutdown all || true
          echo "Launching iOS Simulator"
          xcrun simctl boot "iPhone 15 Pro"
          echo "Installing app on Simulator"
          xcrun simctl install booted "${{ env.APP_PATH }}"
              
      - name: Run e2e tests (3 retries)
        timeout-minutes: 10 
        run: |
          i=0
          while [ $i -le 2 ]; do
          $HOME/.maestro/bin/maestro test e2e-new/test.yaml && break
          let i=i+1
          if [ $i -eq 3 ]; then
            echo "Failed after 3 attempts"
            exit 1
          fi
          done

      - name: Cleanup Derived Data
        if: always()
        run: |
          echo "Cleaning up derived data..."
          rm -rf ios/temp_build
          echo "Cleanup complete."

      - name: Shutdown and clean up simulator
        if: always()
        run: |
          echo "Shutting down all simulators"
          xcrun simctl shutdown all
          echo "Erasing all simulators"
          xcrun simctl erase all
     
      - name: Upload Test Artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: detox-artifacts
          path: artifacts/**

