name: iOS e2e tests

on: [pull_request, workflow_dispatch]

jobs:
  ios-e2e:
    runs-on: self-hosted  # Corrected: Removed the square brackets for a single item list
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - name: Initial Debug - Check Current Directory and Files
        run: |
          echo "Checking current directory and files..."
          pwd
          ls -la

      - name: Set up github keys
        run: |
          echo "Setting up SSH for git operations..."
          git config core.sshCommand "ssh -i ~/.ssh/id_ed25519 -F /dev/null"

      - name: Set up ENV vars & scripts
        run: |
          source ~/.bashrc
          git clone git@github.com:rainbow-me/rainbow-env.git
          mv rainbow-env/dotenv .env && rm -rf rainbow-env 
          eval $CI_SCRIPTS
          sed -i'' -e "s/IS_TESTING=false/IS_TESTING=true/" .env && rm -env-e

      - name: Debug - Check .env File Post-Setup
        run: |
          echo "Checking if .env file was correctly set up..."
          if [ -f .env ]; then
            echo ".env file exists."
          else
            echo ".env file does not exist."
          fi

      - name: Install deps via Yarn
        run: yarn setup-ci

      - name: Check for frozen lockfile
        run: yarn check-lockfile

      - name: Audit CI
        run: yarn audit-ci --config audit-ci.jsonc

      - name: Lint
        run: yarn lint:ci

      - name: Install Pods
        run: |
          cd ios
          bundle install
          pod install --repo-update
          cd ..

      - name: Debug - Verify Pod Installation
        run: |
          echo "Verifying Pod installation..."
          cd ios
          ls -la Pods
          cd ..

      - name: Rebuild detox cache
        run: |
          ./node_modules/.bin/detox clean-framework-cache && ./node_modules/.bin/detox build-framework-cache

      - name: Build the app in Release mode
        run: ./node_modules/.bin/detox build --configuration ios.sim.release

      - name: Run iOS e2e tests
        run: ./node_modules/.bin/detox test -R 5 --configuration ios.sim.release --forceExit --bail
